### PR TITLE
Add GCS as a cache backend option

### PR DESCRIPTION
**Pull request by miselin**
Using [GCS S3 interop](https://cloud.google.com/storage/docs/interoperability) sort of works, but native support for GCS would be nicer.

I've added the backend to the storage test, but there will need to be credentials in there first and a GCS bucket created to support the test I think.

### CODE REVIEW

**Review by pacharrin — APPROVED** [review]

**Comment by lucaspin** [comment]
Thanks for the pull request @miselin!

All looks great to me. I only see one thing we could change here: the S3 backend uses the `SEMAPHORE_PROJECT_ID` environment variable (which is readily available in jobs) to prefix objects in the bucket. That allows multiple Semaphore projects to use the same S3 bucket for their cache, which is usually easier than having one bucket per Semaphore project. Using that for the GCS backend would also be nice.

Regarding the tests, we use minio to mock the S3 backend. We can use it to mock the GCS one as well.

**Review by lucaspin — APPROVED** [review]

**Pull request merged**
