### PR TITLE
Fix automatic go restore

### PR DESCRIPTION
**Pull request by lucaspin**

### CODE REVIEW

**Comment by shiroyasha** [comment]
@bogyo210: @lucaspin will need help with releasing this to production. Can you help him? 🙏

**Comment by bogyo210** [comment]
> @bogyo210: @lucaspin will need help with releasing this to production. Can you help him?

Doing it right now. Will get back with results in a few minutes.

**Review by bogyo210 — APPROVED** [review]

**Comment by lucaspin** [comment]
Should I merge this? Not really sure how the release for the toolbox works

**Comment by bogyo210** [comment]
> Should I merge this? Not really sure how the release for the toolbox works

You shall merge it, error was related to IP change in our registry.

**Pull request merged**
